### ISSUE TITLE
gettin error on datapack for mekfission recipe

### ISSUE THREAD

**Issue by Xplodin** [North-West-Wind/MekanismFissionRecipe#8]
[16Nov2022 00:13:00.258] [Render thread/ERROR] [mezz.jei.gui.recipes.RecipeLayout/]: Error caught from Recipe Category: mekanism:fission
java.lang.IllegalArgumentException: capacityMb must be > 0
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.0.1-jre.jar%2329!/:?]
	at mezz.jei.gui.recipes.builder.RecipeSlotBuilder.setFluidRenderer(RecipeSlotBuilder.java:75) ~[jei-1.18.2-9.7.2.281.jar%23268!/:9.7.2.281]
	at mekanism.client.jei.BaseRecipeCategory.initFluid(BaseRecipeCategory.java:246) ~[Mekanism-1.18.2-10.2.5.465.jar%23298!/:10.2.5]
	at ml.northwestwind.fissionrecipe.jei.FissionReactorRecipeCategory.setRecipe(FissionReactorRecipeCategory.java:68) ~[tiered-fissionrecipe-2.0.1-1.18.2.jar%23429!/:2.0.1]
	at ml.northwestwind.fissionrecipe.jei.FissionReactorRecipeCategory.setRecipe(FissionReactorRecipeCategory.java:35) ~[tiered-fissionrecipe-2.0.1-1.18.2.jar%23429!/:2.0.1]
	at mezz.jei.gui.recipes.RecipeLayout.setRecipeLayout(RecipeLayout.java:77) ~[jei-1.18.2-9.7.2.281.jar%23268!/:9.7.2.281]
	at mezz.jei.gui.recipes.RecipeLayout.create(RecipeLayout.java:57) ~[jei-1.18.2-9.7.2.281.jar%23268!/:9.7.2.281]
	at mezz.jei.gui.recipes.RecipeGuiLogic.getRecipeLayouts(RecipeGuiLogic.java:191) ~[jei-1.18.2-9.7.2.281.jar%23268!/:9.7.2.281]
	at mezz.jei.gui.recipes.RecipeGuiLogic.getRecipeLayouts(RecipeGuiLogic.java:175) ~[jei-1.18.2-9.7.2.281.jar%23268!/:9.7.2.281]
	at mezz.jei.gui.recipes.RecipesGui.updateLayout(RecipesGui.java:515) ~[jei-1.18.2-9.7.2.281.jar%23268!/:9.7.2.281]
	at mezz.jei.gui.recipes.RecipesGui.onStateChange(RecipesGui.java:572) ~[jei-1.18.2-9.7.2.281.jar%23268!/:9.7.2.281]
	at mezz.jei.gui.recipes.RecipeGuiLogic.nextPage(RecipeGuiLogic.java:240) ~[jei-1.18.2-9.7.2.281.jar%23268!/:9.7.2.281]
	at mezz.jei.gui.recipes.RecipesGui.m_6050_(RecipesGui.java:323) ~[jei-1.18.2-9.7.2.281.jar%23268!/:9.7.2.281]
	at net.minecraft.client.MouseHandler.m_91526_(MouseHandler.java:140) ~[client-1.18.2-20220404.173914-srg.jar%23461!/:?]
	at net.minecraft.client.MouseHandler.m_168096_(MouseHandler.java:189) ~[client-1.18.2-20220404.173914-srg.jar%23461!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.18.2-20220404.173914-srg.jar%23461!/:?]
	at net.minecraft.client.MouseHandler.m_91575_(MouseHandler.java:188) ~[client-1.18.2-20220404.173914-srg.jar%23461!/:?]
	at org.lwjgl.glfw.GLFWScrollCallbackI.callback(GLFWScrollCallbackI.java:37) ~[lwjgl-glfw-3.2.2.jar%2348!/:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar%2344!/:build 10]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar%2348!/:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:204) ~[client-1.18.2-20220404.173914-srg.jar%23461!/:?]
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:333) ~[client-1.18.2-20220404.173914-srg.jar%23461!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1068) ~[client-1.18.2-20220404.173914-srg.jar%23461!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%23461!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23461!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.84.jar%2317!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]

datapack: 
[beanpack.zip](https://github.com/North-West-Wind/MekanismFissionRecipe/files/10018279/beanpack.zip)

**Comment by Xplodin** [comment]
side note: viewing the recipe will show a blank fission recipe instead of my own, its like it registered but isnt showing

**Comment by North-West-Wind** [comment]
Well I cannot verify that as I don't have your kubejs gas, but I attempted to fix it.
See if [this](https://www.curseforge.com/minecraft/mc-mods/mekanism-fission-recipe/files/4095138) works?

**Comment by Xplodin** [comment]
![image](https://user-images.githubusercontent.com/13007677/202805675-da87ad2b-5a40-4be1-a762-cb5ae42b9867.png)
well the kubejs is actually a liquid. Im trying it as coolant but cant get it to show up.
Does it need to be a gas?

**Comment by North-West-Wind** [comment]
Can you send me the kubejs files too?

**Comment by Xplodin** [comment]
onEvent('fluid.registry', event => {
	event.create('beanonium_')
    .thickTexture(0x5e4714)
    .bucketColor(0x5e4714)
    .displayName('Beanonium')
  })

**Comment by North-West-Wind** [comment]
I did some more testing. It seems it is just wrong syntax for your datapack. The `beanonium_` you created is a fluid, not a tag, so in the recipe file you should use `fluid` instead of `tag` in the `input` object.

<details>
<summary>Try this for your <code>beaconator.json</code></summary>

```json
{
  "type": "mekanism:fluid_coolant",
  "input": {
    "tag": "kubejs:beanonium_",
    "amount": 1
  },
  "output": {
    "gas": "mekanism:steam",
    "amount": 10
  },
  "efficiency": 4
}
```
</details>

**Comment by Xplodin** [comment]
> I did some more testing. It seems it is just wrong syntax for your datapack. The `beanonium_` you created is a fluid, not a tag, so in the recipe file you should use `fluid` instead of `tag` in the `input` object.
> 
> Try this for your `beaconator.json`
> ```json
> {
>   "type": "mekanism:fluid_coolant",
>   "input": {
>     "fluid": "kubejs:beanonium_",
>     "amount": 1
>   },
>   "output": {
>     "gas": "mekanism:steam",
>     "amount": 10
>   },
>   "efficiency": 4
> }
> ```

ah crap I mustve sent the wrong files and forgot to exchange em out.
Im gonna test right now with fluid instead of tag
thank you for pointing that out

**Comment by Xplodin** [comment]
Awesome work, I can see the fluid in the reactor. Thank you for this amazing addon, its given me ideas for my modpack.

Without this addon, I dont think its remotely possible for me to add custom coolants, fluids, gasses, reactor etc stuff.

**Comment by Xplodin** [comment]
Hey I recently updated the script to 1.19.2 and used updated stuff for 1.19.2 however the fluid recipe for mek doesnt show up in the reactor coolants list.

this error shows up in latest.log
Failed to parse recipe 'mekanism:coolant/beanactor[mekanism:fluid_coolant]'! Falling back to vanilla: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsDouble()" because the return value of "com.google.gson.JsonObject.get(String)" is null
[01Apr2023 11:15:38.997] [Render thread/WARN] [KubeJS Server/]: Failed to parse recipe mekanism:coolant/beanactor[mekanism:fluid_coolant]: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsDouble()" because the return value of "com.google.gson.JsonObject.get(String)" is null

**Comment by Xplodin** [comment]
oops datapack was wrong sorry
